Fixes win10build v2
radareorg/r2ghidra pull request #17
Opened 2021-02-04 14:09 UTC by sab24

Sorry for all the mess, now this is updated with the three improvements mentioned in #15

2021-02-04 14:25 UTC, sab24 commented
```
r2r -L db/extras
Running from /home/sab24/Downloads/r2ghidra/test
Skipping /home/sab24/Downloads/r2ghidra/test/db/extras/r2ghidra because of R2R_SKIP_ARCHOS == 1.
Skipping /home/sab24/Downloads/r2ghidra/test/db/extras/asm_ghidra because of R2R_SKIP_ARCHOS == 1.
Skipping /home/sab24/Downloads/r2ghidra/test/db/extras/ghidra because of R2R_SKIP_ARCHOS == 1.
Skipping /home/sab24/Downloads/r2ghidra/test/db/extras/anal_ghidra because of R2R_SKIP_ARCHOS == 1.
Loaded 0 tests.
Skipping json tests because jq is not available.

Finished in 0 seconds.
```

I suggest upgrading to Archlinux :)

2021-02-04 17:59 UTC, trufae requested changes
I think ci.yml only runs in master. Can you change this to test your pr? See how its done in r2cutter or r2 for example

thank you!!

2021-02-04 17:59 UTC, trufae commented on cmake/FindRadare2.cmake
> +						../radare2/include/libr/sdb
Wrong indent

2021-02-04 17:59 UTC, trufae commented on cmake/FindRadare2.cmake
> +	set (Radare2_LIBRARIES "" )
Dont add a space here. Follow the style of the rest of the file

2021-02-05 15:19 UTC, sab24 commented
I found in DEVELOPERS: "A tab is considered as 8 chars." so this is the right punctuation for the cmake file right?

2021-02-05 17:33 UTC, trufae commented
i will probably change that DEVELOPERS thing to follow the r2 coding style, seems a bit inconsistent otherwise to me.

2021-02-05 17:34 UTC, merged

2021-02-05 17:35 UTC, trufae commented
What do you mean to use archlinux? the ARCHOS tests are disabled because they require specific stuff from your system to work. and right now this is only suposed to run in ubuntu, i disabled thembecause TCC built binaries contain different sections and maps when debugged and broke some tests. actually ubuntu have LTS which is better for testing, i love archlinux, but using it in the CI may result in unexpected brokenness